In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("filmler_clean.csv")

In [3]:
df.head()

film adi  \
0                                       Bergen   
1                                Kirpi Sonic 2   
2  Fantastik Canavarlar: Dumbledore'un Sırları   
3                               Aykut Enişte 2   
4                                      Morbius   

                                    ozet ve detaylar  \
0  Arabeskin unutulmayan kadın seslerinden biri o...   
1  Çocuk filmi \n\n\nKirpi Sonic filminin devam h...   
2  Karanlık büyücü Gellert Grindelwald, büyücülük...   
3  Aykut Enişte 2, sevdiği kadınla evlilik arifes...   
4  Morbius, hastalığına deva bulmaya çalışırken b...   

                                  tur  \
0              ['Dram', 'Biyografik']   
1     ['Animasyon', 'Aile', 'Macera']   
2             ['Fantastik', 'Macera']   
3                          ['Komedi']   
4  ['Aksiyon', 'Fantastik', 'Macera']   

                                           oyuncular  \
0  ['Farah Zeynep Abdullah', 'Erdal Beşikçioğlu',...   
1              ['Jim Carrey', 'James Marsden', None]   
2   ['Eddie Redmayne', 'Jude Law', 'Mads Mikkelsen']   
3  ['Cem Gelinoğlu', 'Melis Babadağ', 'Hakan Yılm...   
4  ['Jared Leto', 'Matt Smith (XI)', 'Adria Arjona']   

                          yonetmen  vizyon tarihi     sure  \
0  ['Mehmet Binay', 'Caner Alper']    4 Mart 2022  2s 26dk   
1                  ['Jeff Fowler']   8 Nisan 2022   2s 2dk   
2                  ['David Yates']  15 Nisan 2022  2s 22dk   
3                ['Onur Bilgetay']  3 Aralık 2021  1s 55dk   
4              ['Daniel Espinosa']   1 Nisan 2022  1s 45dk   

                                               clean  
0  arabesk unutmak kadın ses o Bergen inmek hayat...  
1  çocuk film kirpi Sonic film deva halka o yapım...  
2  Karanlık büyü Gellert Grindelwald büyü Dünya k...  
3  Aykut enişte 2 sevmek kadın ev arife kendi tür...  
4  Morbius hastalık deva bulmak Çalışır bambaşka ...

In [4]:
oyuncular = df["oyuncular"].str.replace("[","")
oyuncular = oyuncular.str.replace("]","")

tur = df["tur"].str.replace("[","")
tur = tur.str.replace("]","")

C:\Users\c-e-m\AppData\Local\Temp\ipykernel_20660\734169021.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  oyuncular = df["oyuncular"].str.replace("[","")
C:\Users\c-e-m\AppData\Local\Temp\ipykernel_20660\734169021.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  oyuncular = oyuncular.str.replace("]","")
C:\Users\c-e-m\AppData\Local\Temp\ipykernel_20660\734169021.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  tur = df["tur"].str.replace("[","")
C:\Users\c-e-m\AppData\Local\Temp\ipykernel_20660\734169021.py:5

In [5]:
len(oyuncular)

5261

In [6]:
word2idx = {}
idx2word = {}
tur_word2idx = {}
tur_idx2word = {}

In [7]:
i = 0
for cell in oyuncular:
    words = cell.split()
    for word in words:
        if word in word2idx:
            continue
        word2idx[word] = i
        idx2word[i] = word
        i += 1
j = 0
for cell in tur:
    words = cell.split()
    for word in words:
        if word in tur_word2idx:
            continue
        tur_word2idx[word] = j
        tur_idx2word[j] = word
        j += 1

In [8]:
word2idx

{"'Farah": 0,
 'Zeynep': 1,
 "Abdullah',": 2,
 "'Erdal": 3,
 "Beşikçioğlu',": 4,
 "'Tilbe": 5,
 "Saran'": 6,
 "'Jim": 7,
 "Carrey',": 8,
 "'James": 9,
 "Marsden',": 10,
 'None': 11,
 "'Eddie": 12,
 "Redmayne',": 13,
 "'Jude": 14,
 "Law',": 15,
 "'Mads": 16,
 "Mikkelsen'": 17,
 "'Cem": 18,
 "Gelinoğlu',": 19,
 "'Melis": 20,
 "Babadağ',": 21,
 "'Hakan": 22,
 "Yılmaz'": 23,
 "'Jared": 24,
 "Leto',": 25,
 "'Matt": 26,
 'Smith': 27,
 "(XI)',": 28,
 "'Adria": 29,
 "Arjona'": 30,
 'None,': 31,
 "'Hazar": 32,
 "Ergüçlü',": 33,
 "'Ozan": 34,
 "Uygun',": 35,
 "'Halil": 36,
 "Babür'": 37,
 "'İsmail": 38,
 "Hacıoğlu',": 39,
 "'Rahman": 40,
 "Başel',": 41,
 "'Alayça": 42,
 "Öztürk'": 43,
 "'Tom": 44,
 "Holland',": 45,
 "'Zendaya',": 46,
 "'Benedict": 47,
 "Cumberbatch'": 48,
 "'Robert": 49,
 "Pattinson',": 50,
 "'Zoë": 51,
 "Kravitz',": 52,
 "'Paul": 53,
 "Dano'": 54,
 "Cumberbatch',": 55,
 "'Elizabeth": 56,
 "Olsen',": 57,
 "'Rachel": 58,
 "McAdams'": 59,
 "'Büşra": 60,
 "Pekin',": 61,
 "'Zeliha":

In [9]:
tur_word2idx

{"'Dram',": 0,
 "'Biyografik'": 1,
 "'Animasyon',": 2,
 "'Aile',": 3,
 "'Macera'": 4,
 "'Fantastik',": 5,
 "'Komedi'": 6,
 "'Aksiyon',": 7,
 "'Dram'": 8,
 "'Aksiyon'": 9,
 "'Macera',": 10,
 "'Fantastik'": 11,
 "'Polisiye',": 12,
 "'Gerilim'": 13,
 "'Biyografik',": 14,
 "'Animasyon'": 15,
 "'Bilimkurgu',": 16,
 "'Gerilim',": 17,
 "'Romantik',": 18,
 "'Erotik'": 19,
 "'Komedi',": 20,
 "'Aile'": 21,
 "'Tarihi'": 22,
 "'Korku'": 23,
 "'Romantik'": 24,
 "'Bilimkurgu'": 25,
 "'Polisiye'": 26,
 "'Korku',": 27,
 "'Dramatik": 28,
 "komedi'": 29,
 "'Müzik'": 30,
 "'Savaş": 31,
 "filmi',": 32,
 "'Erotik',": 33,
 "'Tarihi',": 34,
 "filmi'": 35,
 "'Casusluk'": 36,
 "'Müzikal'": 37,
 "'Bollywood'": 38,
 "'Bollywood',": 39,
 "'Epik'": 40,
 "'Western',": 41,
 "'Müzikal',": 42,
 "'Dövüş',": 43,
 "komedi',": 44,
 "'Epik',": 45,
 "'Casusluk',": 46,
 "'Western'": 47,
 "'Biyografik": 48,
 "',": 49,
 "'Müzik',": 50,
 "'Mahkeme'": 51,
 "'Mahkeme',": 52,
 "'Animasyon": 53,
 "'Dövüş'": 54,
 "'Experimental'": 5

In [10]:
len(word2idx)

9818

In [11]:
import numpy as np

In [12]:
film_sayisi = len(oyuncular)
film_sayisi_tur = len(tur)

vocab_size = len(word2idx)
vocab_size_tur = len(tur_word2idx)

In [13]:
filmler = np.zeros((film_sayisi, vocab_size))
filmler_tur = np.zeros((film_sayisi_tur, vocab_size_tur))

In [14]:
filmler.shape

(5261, 9818)

In [15]:
for i, cell in enumerate(oyuncular):
    words = cell.split()
    for word in words:
        wordIndex = word2idx[word]
        filmler[i][wordIndex] += 1
        
        
        
for i, cell in enumerate(tur):
    words = cell.split()
    for word in words:
        wordIndex = tur_word2idx[word]
        filmler_tur[i][wordIndex] += 1

In [16]:
filmler[7][:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
doc_frequencies = {}
tur_doc_frequencies = {}

In [18]:
# 1 - 5 dk sürebilir
for word in word2idx:
    doc_count = 0
    for film in oyuncular:
        if word in film:
            doc_count += 1
    
    doc_frequencies[word] = doc_count
    
for word in tur_word2idx:
    doc_count = 0
    for film in tur:
        if word in film:
            doc_count += 1
    
    tur_doc_frequencies[word] = doc_count    


In [19]:
sorted_frequencies = sorted(doc_frequencies, key=doc_frequencies.get, reverse=True)
tur_sorted_frequencies = sorted(tur_doc_frequencies, key=tur_doc_frequencies.get, reverse=True)



In [20]:
for word in sorted_frequencies[:10]:
    print(word, doc_frequencies[word])

la 952
'Ma 580
de 578
'Jo 477
De 468
da 445
Al 438
Ka 369
None 364
None, 349


In [21]:
for word in sorted_frequencies[150:160]:
    print(word, doc_frequencies[word])

'Sara 44
'Jeff 44
'Colin 44
Thomas 43
'Martin 42
Freeman' 42
Moore' 41
'Emily 41
'Anna 41
Christian 41


In [22]:
for word in sorted_frequencies[-10:]:
    print(word, doc_frequencies[word])

Mille' 1
'Frankie 1
Muniz' 1
Thulin', 1
'Xander 1
Berkeley', 1
Tezcan', 1
Tarıman', 1
Ağlamaz' 1
Gnecco', 1


In [23]:
# 1 - 5 dk sürebilir

filmler_tf_idf = np.zeros((film_sayisi, vocab_size))
film_sayisi = len(oyuncular)

display(filmler_tf_idf.shape)
"""
for i, film in enumerate(filmler):
    if i % 1000 == 0:
        print(f"{i} inci film işleniyor...")
    for j, tf in enumerate(film):
        idf = 0
        if tf > 0:
            idf = np.log(film_sayisi / (doc_frequencies[idx2word[j]] + 1)) + 1
        tf_idf_score = tf * idf
        filmler_tf_idf[i][j] = tf_idf_score
       
"""   
    
    
    
tur_filmler_tf_idf = np.zeros((film_sayisi_tur, vocab_size_tur))
tur_film_sayisi = len(tur)

display(filmler_tur.shape)



for i, film in enumerate(filmler_tur):
    if i % 1000 == 0:
        print(f"{i} inci film işleniyor...")
    for j, tf in enumerate(film):
        idf = 0
        if tf > 0:
            idf = np.log(tur_film_sayisi / (tur_doc_frequencies[tur_idx2word[j]] + 1)) + 1
        tur_tf_idf_score = tf * idf
        tur_filmler_tf_idf[i][j] = tur_tf_idf_score        

(5261, 9818)

(5261, 61)

0 inci film işleniyor...
1000 inci film işleniyor...
2000 inci film işleniyor...
3000 inci film işleniyor...
4000 inci film işleniyor...
5000 inci film işleniyor...


In [24]:
print(filmler_tf_idf[0][:10])
print(filmler[0][:10])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]


In [25]:
def cos_sim(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [26]:
def film_2_str(row_index):
    film = df.iloc[row_index]
    adi = film['film adi']
    turu = film['tur']
    ozet = film['ozet ve detaylar']
    oyuncular = film['oyuncular']
    if len(ozet) > 150:
        ozet = ozet[:150] + "..."

    return f"Film adı: {adi} \nTürü: {turu} \nOyuncular: {oyuncular} \nÖzeti: {ozet}"

In [27]:
print(film_2_str(0))

Film adı: Bergen 
Türü: ['Dram', 'Biyografik'] 
Oyuncular: ['Farah Zeynep Abdullah', 'Erdal Beşikçioğlu', 'Tilbe Saran'] 
Özeti: Arabeskin unutulmayan kadın seslerinden biri olan Bergen'in hayatını anlatan filmde, Bergen olarak bilinen Belgin'in Ankara'dan Adana'ya, oradan da ya...


In [28]:
def most_similar_films(film_adi, benzer_film_sayisi):
    film_indexi = df[df["film adi"] == film_adi].index[0]
    print("Aranan Film:")
    print(film_2_str(film_indexi))
    print()
    print("* " * 30)
    print()

    benzerlikler = []
    
    tur_benzerlikler = []
    

    sorgu_film = filmler_tf_idf[film_indexi]
    
    tur_sorgu_film = tur_filmler_tf_idf[film_indexi]

    for vec in filmler_tf_idf:
        benzerlik = cos_sim(sorgu_film, vec)
        benzerlikler.append(benzerlik)
        
    for vec in tur_filmler_tf_idf:
        tur_benzerlik = cos_sim(tur_sorgu_film, vec)
        tur_benzerlikler.append(tur_benzerlik)        
    
    print(np.array(tur_benzerlikler).shape)
    
    total_benzerlik = np.add(np.array(tur_benzerlikler)*0.4,np.array(benzerlikler)*0.6)
    
    en_benzer_film_indexleri = (- np.array(total_benzerlik)).argsort()[:benzer_film_sayisi + 1]
    print("Benzer Filmler:\n")
    for i, film_idx in enumerate(en_benzer_film_indexleri[1:]):
        print(str(i+1) + ") " + film_2_str(film_idx))
        print()
        print("- " * 20)
        print()
    

In [29]:
df.iloc[:10]["film adi"]

0                                         Bergen
1                                  Kirpi Sonic 2
2    Fantastik Canavarlar: Dumbledore'un Sırları
3                                 Aykut Enişte 2
4                                        Morbius
5                                        Kırmızı
6                                            Kar
7                    Kesişme: İyi ki Varsın Eren
8                     Örümcek-Adam Eve Dönüş Yok
9                                     The Batman
Name: film adi, dtype: object

In [30]:
most_similar_films("Kirpi Sonic 2", 3)

Aranan Film:
Film adı: Kirpi Sonic 2 
Türü: ['Animasyon', 'Aile', 'Macera'] 
Oyuncular: ['Jim Carrey', 'James Marsden', None] 
Özeti: Çocuk filmi 


Kirpi Sonic filminin devam halkası olan yapımda, insan biçiminde bir kirpi olan Sonic'in atıldığı maceralar konu ediliyor. Green Hills’...

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 



C:\Users\c-e-m\AppData\Local\Temp\ipykernel_20660\771313959.py:2: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))


(5261,)
Benzer Filmler:

1) Film adı: Gitmek: Benim Marlon ve Brandom 
Türü: ['Dövüş', 'Dram', 'Romantik'] 
Oyuncular: ['Ayça Damgacı'] 
Özeti: "Gitmek: Benim Marlon ve Brandom", oryantalist olma tuzağına düşmeyen, naif, "batılı" bir Türk kızının "doğulu" bir orta yaşlı adama gönlünü kaptırmas...

- - - - - - - - - - - - - - - - - - - - 

2) Film adı: Demir Leydi 
Türü: ['Biyografik', 'Dram', 'Tarihi'] 
Oyuncular: ['Meryl Streep', 'Jim Broadbent', 'Susan Brown'] 
Özeti: 2 Nisan 1982'de Arjantin'in Falkland ve Güney Georgia Adalarını işgal etmesi ile başlayan ve altı hafta süren Falkland Savaşı'nda yaşanan krizi odak n...

- - - - - - - - - - - - - - - - - - - - 

3) Film adı: King Kong 
Türü: ['Fantastik', 'Korku', 'Gerilim'] 
Oyuncular: ['Fay Wray', 'Robert Armstrong', 'Bruce Cabot'] 
Özeti: Bir kurban törenine hesapta olmayan bir şekilde karışmak ve yaşananlara müdahale etmeye çalışmak herkesi huzursuz edecektir illa ki. Carl Denham yönet...

- - - - - - - - - - - - - - - - - - - - 
